version: '3.3'

services:
  web:
    build:
      context: .
      dockerfile: ./compose/production/django/Dockerfile
    restart: always
    command: /start
    volumes:
      - static_volume:/armadion/staticfiles
      - media_volume:/armadion/mediafiles
      - logs:/armadion/logs
    expose:
      - 8000
    env_file:
      - .env.prod
    depends_on:
      - db

  redis:
    image: redis:7.0.5-alpine

  celery:
    build:
      context: .
      dockerfile: ./compose/production/django/Dockerfile
    command: /start-celeryworker
    env_file:
      - .env.prod
    depends_on:
      - db
      - redis
  db:
    image: postgres:15.4-bullseye
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env.prod.db
    ports:
      - "5431:5432"
  nginx:
    image: nginx:latest
    ports:
      - 80:80
      - 443:443
    restart: always
    volumes:
      - ./compose/production/nginx:/etc/nginx/conf.d/:ro
      - ./certbot/www:/var/www/certbot/:ro
      - static_volume:/armadion/staticfiles
      - media_volume:/armadion/mediafiles
  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./certbot/www/:/var/www/certbot/:rw
volumes:
  postgres_data:
  static_volume:
  media_volume:
  logs: