# Generated by Django 4.2.5 on 2023-11-08 14:50

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Door',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('article', models.CharField(blank=True, max_length=255, null=True)),
                ('click_counter', models.IntegerField(default=0)),
                ('in_stock', models.BooleanField()),
                ('slug', models.SlugField(max_length=255)),
                ('image_one', models.ImageField(upload_to='door_photos/')),
                ('image_two', models.ImageField(blank=True, null=True, upload_to='door_photos/')),
                ('image_three', models.ImageField(blank=True, null=True, upload_to='door_photos/')),
                ('image_four', models.ImageField(blank=True, null=True, upload_to='door_photos/')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField(blank=True, null=True)),
                ('delivery', models.TextField(blank=True, null=True)),
                ('payment', models.TextField(blank=True, null=True)),
                ('safeguards', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Двери',
            },
        ),
        migrations.CreateModel(
            name='Filter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Фильтры',
            },
        ),
        migrations.CreateModel(
            name='FilterValue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255)),
                ('filter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filter_values', to='doors.filter')),
            ],
            options={
                'verbose_name_plural': 'Фильтры: значения',
            },
        ),
        migrations.CreateModel(
            name='FeatureCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=255)),
                ('door', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feature_categories', to='doors.door')),
            ],
            options={
                'verbose_name_plural': 'Характеристики: категории',
            },
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('value', models.CharField(max_length=200)),
                ('name_slug', models.SlugField(max_length=255)),
                ('value_slug', models.SlugField(max_length=255)),
                ('feature_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='doors.featurecategory')),
            ],
            options={
                'verbose_name_plural': 'Характеристики',
            },
        ),
    ]
