# Generated by Django 4.2.5 on 2023-11-12 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doors', '0002_filter_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filter',
            name='type',
            field=models.CharField(choices=[('price_filter', 'Фильтр по цене'), ('category_filter', 'Фильтр по категории'), ('limitoffset_filter', 'Фильтр по количеству')], default='category_filter', max_length=255),
        ),
    ]
