# Generated by Django 4.2.5 on 2023-11-15 07:41

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('doors', '0004_alter_filter_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='door',
            name='image_four',
        ),
        migrations.RemoveField(
            model_name='door',
            name='image_one',
        ),
        migrations.RemoveField(
            model_name='door',
            name='image_three',
        ),
        migrations.RemoveField(
            model_name='door',
            name='image_two',
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(upload_to='images/')),
                ('mimetype', models.CharField(max_length=100)),
                ('door', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='doors.door')),
            ],
        ),
    ]
