# Generated by Django 4.2.5 on 2023-11-15 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doors', '0005_remove_door_image_four_remove_door_image_one_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'verbose_name_plural': 'Фото'},
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to='mediafiles/doors/'),
        ),
    ]
