# Generated by Django 4.2.5 on 2023-12-19 09:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doors', '0006_alter_image_options_alter_image_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='featurecategory',
            name='door',
        ),
        migrations.AddField(
            model_name='feature',
            name='door',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='feature_categories', to='doors.door'),
            preserve_default=False,
        ),
    ]
