# Generated by Django 4.2.5 on 2023-12-19 09:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doors', '0007_remove_featurecategory_door_feature_door'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='featurecategory',
            options={'verbose_name_plural': 'Категории характеристик'},
        ),
        migrations.AlterField(
            model_name='feature',
            name='door',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doors', to='doors.door'),
        ),
        migrations.AlterField(
            model_name='feature',
            name='feature_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feature_categories', to='doors.featurecategory'),
        ),
    ]
