# Generated by Django 4.2.5 on 2023-12-19 09:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doors', '0008_alter_featurecategory_options_alter_feature_door_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feature',
            name='door',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='doors.door'),
        ),
        migrations.AlterField(
            model_name='feature',
            name='feature_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='doors.featurecategory'),
        ),
    ]
